import type { Scene, StrategyConfig, UserProfile, Video } from "./types";

const metric = (
  exposure: number,
  validPlayRate: number,
  finishRate: number,
  interactionRate: number,
  negativeRate: number,
  reportRate: number,
  gameReturnRate: number,
  nextDayReturnRate: number,
) => ({ exposure, validPlayRate, finishRate, interactionRate, negativeRate, reportRate, gameReturnRate, nextDayReturnRate });

export const videos: Video[] = [
  {
    id: "SK_0001",
    title: "这把双扣最后一炸直接翻盘",
    author: "官方运营号",
    authorType: "官方",
    source: "自有录屏",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["炸弹", "反炸", "残局"],
    region: ["浙江"],
    duration: 38,
    orientation: "竖屏",
    primaryType: "爽点牌局",
    secondaryType: "极限翻盘",
    format: "录屏讲解",
    depth: "中层",
    topics: ["炸弹使用", "极限翻盘"],
    keywords: ["炸弹", "反炸", "残局", "翻盘", "队友配合"],
    highlights: ["逆风翻盘", "一手定胜负"],
    emotions: ["爽", "紧张", "解气"],
    targetStages: ["活跃", "低活", "回流"],
    targetSkills: ["进阶", "高手"],
    targetRegions: ["浙江"],
    targetInterests: ["双扣用户", "地方棋牌用户"],
    scenes: ["首页推荐流", "大厅停留", "局后结算", "退出前", "Push落地"],
    businessGoal: "促活",
    action: "优先分发",
    priority: "S",
    quality: 0.94,
    ageHours: 8,
    isUgc: false,
    racePool: "T4",
    authorCredit: 0.96,
    operationBoost: 0.08,
    strongGuide: true,
    thumbnail: "/thumbs/shot-06.jpg",
    metrics: metric(18420, 0.78, 0.63, 0.17, 0.012, 0.001, 0.132, 0.21),
  },
  {
    id: "SK_0002",
    title: "双扣新手一分钟看懂基本规则",
    author: "双扣教学号",
    authorType: "达人",
    source: "达人授权",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["基础流程", "牌型", "胜负结算"],
    region: ["浙江", "其他"],
    duration: 55,
    orientation: "竖屏",
    primaryType: "规则入门",
    secondaryType: "基础流程",
    format: "口播",
    depth: "浅层",
    topics: ["基础玩法", "快速入门"],
    keywords: ["牌型", "双扣", "单扣", "平扣"],
    highlights: ["快速入门"],
    emotions: ["清晰", "易懂"],
    targetStages: ["新增", "回流"],
    targetSkills: ["新手"],
    targetRegions: ["浙江", "其他"],
    targetInterests: ["双扣用户", "棋牌用户"],
    scenes: ["首页推荐流", "游戏详情页", "Push落地"],
    businessGoal: "拉新",
    action: "常规分发",
    priority: "A",
    quality: 0.88,
    ageHours: 45,
    isUgc: false,
    racePool: "T4",
    authorCredit: 0.9,
    operationBoost: 0.02,
    strongGuide: true,
    thumbnail: "/thumbs/shot-01.jpg",
    metrics: metric(12600, 0.71, 0.58, 0.09, 0.009, 0.001, 0.164, 0.19),
  },
  {
    id: "SK_0003",
    title: "高手打双扣为什么不急着炸",
    author: "双扣老王",
    authorType: "达人",
    source: "达人授权",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["忍炸", "保炸", "控牌"],
    region: ["浙江"],
    duration: 68,
    orientation: "竖屏",
    primaryType: "技巧教学",
    secondaryType: "炸弹使用",
    format: "录屏讲解",
    depth: "深层",
    topics: ["忍炸", "关键决策"],
    keywords: ["炸弹", "忍炸", "保炸", "控牌"],
    highlights: ["关键决策", "老玩家都懂"],
    emotions: ["思考", "紧张", "解气"],
    targetStages: ["活跃", "回流"],
    targetSkills: ["进阶", "高手"],
    targetRegions: ["浙江"],
    targetInterests: ["双扣用户"],
    scenes: ["首页推荐流", "游戏详情页", "局后结算"],
    businessGoal: "留存",
    action: "常规分发",
    priority: "A",
    quality: 0.91,
    ageHours: 28,
    isUgc: false,
    racePool: "T4",
    authorCredit: 0.92,
    operationBoost: 0,
    strongGuide: false,
    thumbnail: "/thumbs/shot-03.jpg",
    metrics: metric(8350, 0.69, 0.51, 0.14, 0.008, 0.001, 0.118, 0.24),
  },
  {
    id: "SK_0004",
    title: "队友这一手让牌太关键了",
    author: "温州阿强",
    authorType: "玩家",
    source: "玩家投稿",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["让牌", "接风", "送队友"],
    region: ["温州", "浙江"],
    duration: 46,
    orientation: "竖屏",
    primaryType: "实战复盘",
    secondaryType: "队友配合复盘",
    format: "录屏讲解",
    depth: "中层",
    topics: ["队友配合", "关键三手"],
    keywords: ["让牌", "接风", "送队友", "残局"],
    highlights: ["神级配合", "关键决策"],
    emotions: ["爽", "共鸣"],
    targetStages: ["活跃", "低活", "回流"],
    targetSkills: ["进阶", "高手"],
    targetRegions: ["温州", "浙江"],
    targetInterests: ["双扣用户", "地方棋牌用户"],
    scenes: ["首页推荐流", "局后结算", "退出前"],
    businessGoal: "促活",
    action: "优先分发",
    priority: "S",
    quality: 0.89,
    ageHours: 13,
    isUgc: true,
    racePool: "T3",
    authorCredit: 0.84,
    operationBoost: 0.03,
    strongGuide: false,
    thumbnail: "/thumbs/shot-04.jpg",
    metrics: metric(2860, 0.76, 0.61, 0.19, 0.014, 0.001, 0.141, 0.27),
  },
  {
    id: "SK_0005",
    title: "新手最容易犯的错误：乱压队友",
    author: "牌局研究所",
    authorType: "内部账号",
    source: "官方素材",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["压牌", "队友配合", "失误"],
    region: ["浙江", "其他"],
    duration: 42,
    orientation: "竖屏",
    primaryType: "失误避坑",
    secondaryType: "乱压队友",
    format: "动画包装",
    depth: "浅层",
    topics: ["新手避坑"],
    keywords: ["压牌", "队友配合", "失误"],
    highlights: ["新手常犯", "队友坑我"],
    emotions: ["懊恼", "搞笑", "共鸣"],
    targetStages: ["新增", "低活"],
    targetSkills: ["新手", "进阶"],
    targetRegions: ["浙江", "其他"],
    targetInterests: ["双扣用户", "棋牌用户"],
    scenes: ["首页推荐流", "游戏详情页", "匹配等待"],
    businessGoal: "留存",
    action: "常规分发",
    priority: "A",
    quality: 0.86,
    ageHours: 70,
    isUgc: false,
    racePool: "T4",
    authorCredit: 0.91,
    operationBoost: 0,
    strongGuide: true,
    thumbnail: "/thumbs/shot-05.jpg",
    metrics: metric(9450, 0.72, 0.57, 0.12, 0.011, 0.001, 0.126, 0.18),
  },
  {
    id: "SK_0006",
    title: "温州老玩家双扣朋友局",
    author: "温州双扣玩家",
    authorType: "达人",
    source: "达人授权",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "地方棋牌",
    gameplay: ["朋友局", "地方玩法"],
    region: ["温州", "浙江"],
    duration: 80,
    orientation: "竖屏",
    primaryType: "地域社交",
    secondaryType: "温州双扣",
    format: "真人出镜",
    depth: "浅层",
    topics: ["地方玩法", "熟人局"],
    keywords: ["方言解说", "朋友局", "老玩家"],
    highlights: ["地域共鸣", "老玩家局"],
    emotions: ["亲切", "搞笑", "共鸣"],
    targetStages: ["低活", "沉默", "回流"],
    targetSkills: ["进阶", "高手"],
    targetRegions: ["温州", "浙江"],
    targetInterests: ["双扣用户", "地方棋牌用户"],
    scenes: ["首页推荐流", "退出前", "Push落地"],
    businessGoal: "召回",
    action: "常规分发",
    priority: "B",
    quality: 0.82,
    ageHours: 18,
    isUgc: true,
    racePool: "T2",
    authorCredit: 0.78,
    operationBoost: 0,
    strongGuide: false,
    thumbnail: "/thumbs/shot-02.jpg",
    metrics: metric(720, 0.74, 0.66, 0.21, 0.016, 0.002, 0.092, 0.31),
  },
  {
    id: "UGC_0101",
    title: "我爸打牌输了以后嘴有多硬",
    author: "牌桌小林",
    authorType: "玩家",
    source: "玩家投稿",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "地方棋牌",
    gameplay: ["朋友局", "输赢反应"],
    region: ["浙江"],
    duration: 29,
    orientation: "竖屏",
    primaryType: "棋牌泛娱乐",
    secondaryType: "牌桌短剧",
    format: "真人出镜",
    depth: "浅层",
    topics: ["亲友局故事", "输赢反应"],
    keywords: ["嘴硬", "亲友局", "打牌段子"],
    highlights: ["反转", "老玩家都懂"],
    emotions: ["搞笑", "共鸣", "轻松"],
    targetStages: ["低活", "沉默", "回流"],
    targetSkills: ["新手", "进阶", "高手"],
    targetRegions: ["浙江"],
    targetInterests: ["双扣用户", "地方棋牌用户"],
    scenes: ["首页推荐流", "匹配等待", "退出前"],
    businessGoal: "召回",
    action: "优先分发",
    priority: "A",
    quality: 0.87,
    ageHours: 5,
    isUgc: true,
    racePool: "T1",
    authorCredit: 0.72,
    operationBoost: 0.04,
    strongGuide: false,
    thumbnail: "/thumbs/final-09.jpg",
    metrics: metric(168, 0.81, 0.72, 0.23, 0.009, 0, 0.075, 0.34),
  },
  {
    id: "UGC_0102",
    title: "最后一张牌掉桌底，三个人都沉默了",
    author: "小林牌桌剧场",
    authorType: "玩家",
    source: "AI生成",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "地方棋牌",
    gameplay: ["朋友局", "残局"],
    region: ["浙江"],
    duration: 31,
    orientation: "竖屏",
    primaryType: "棋牌泛娱乐",
    secondaryType: "牌桌短剧",
    format: "真人出镜",
    depth: "浅层",
    topics: ["牌桌反转", "亲友局故事"],
    keywords: ["最后一张", "反转", "打牌段子"],
    highlights: ["意外反转", "一手定胜负"],
    emotions: ["搞笑", "紧张", "解气"],
    targetStages: ["活跃", "低活", "沉默"],
    targetSkills: ["新手", "进阶", "高手"],
    targetRegions: ["浙江"],
    targetInterests: ["双扣用户", "棋牌用户"],
    scenes: ["首页推荐流", "匹配等待", "退出前"],
    businessGoal: "促活",
    action: "常规分发",
    priority: "A",
    quality: 0.9,
    ageHours: 2,
    isUgc: true,
    racePool: "T1",
    authorCredit: 0.68,
    operationBoost: 0.02,
    strongGuide: false,
    thumbnail: "/thumbs/final-23.jpg",
    metrics: metric(96, 0.84, 0.75, 0.2, 0.008, 0, 0.083, 0.29),
  },
  {
    id: "GD_0201",
    title: "掼蛋残局：这一手该不该拆炸",
    author: "掼蛋研究局",
    authorType: "达人",
    source: "达人授权",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "掼蛋",
    gameCluster: "扑克",
    gameplay: ["残局", "拆炸", "控牌"],
    region: ["江苏", "浙江"],
    duration: 52,
    orientation: "竖屏",
    primaryType: "技巧教学",
    secondaryType: "残局决策",
    format: "录屏讲解",
    depth: "深层",
    topics: ["残局处理", "关键决策"],
    keywords: ["拆炸", "残局", "控牌"],
    highlights: ["关键决策"],
    emotions: ["思考", "紧张"],
    targetStages: ["活跃", "回流"],
    targetSkills: ["进阶", "高手"],
    targetRegions: ["江苏", "浙江"],
    targetInterests: ["掼蛋用户", "棋牌用户"],
    scenes: ["首页推荐流", "局后结算", "游戏详情页"],
    businessGoal: "留存",
    action: "常规分发",
    priority: "A",
    quality: 0.9,
    ageHours: 22,
    isUgc: false,
    racePool: "T4",
    authorCredit: 0.93,
    operationBoost: 0,
    strongGuide: false,
    thumbnail: "/thumbs/shot-07.jpg",
    metrics: metric(6240, 0.66, 0.49, 0.13, 0.009, 0.001, 0.108, 0.2),
  },
  {
    id: "ACT_0301",
    title: "周末双扣冲榜赛，完成三局领头像框",
    author: "赛事中心",
    authorType: "官方",
    source: "官方素材",
    authorized: true,
    copyrightRisk: "低",
    status: "已入库",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["活动", "比赛", "奖励"],
    region: ["浙江", "其他"],
    duration: 24,
    orientation: "竖屏",
    primaryType: "活动赛事",
    secondaryType: "奖励活动",
    format: "动画包装",
    depth: "浅层",
    topics: ["冲榜", "赢奖励"],
    keywords: ["比赛", "奖励", "周末赛"],
    highlights: ["限时奖励"],
    emotions: ["刺激", "参与感"],
    targetStages: ["活跃", "回流"],
    targetSkills: ["新手", "进阶", "高手"],
    targetRegions: ["浙江", "其他"],
    targetInterests: ["双扣用户"],
    scenes: ["首页推荐流", "大厅停留", "Push落地"],
    businessGoal: "转化",
    action: "优先分发",
    priority: "S",
    quality: 0.84,
    ageHours: 6,
    isUgc: false,
    racePool: "T4",
    authorCredit: 0.98,
    operationBoost: 0.22,
    strongGuide: true,
    thumbnail: "/thumbs/final-28.jpg",
    metrics: metric(15200, 0.61, 0.44, 0.08, 0.021, 0.001, 0.186, 0.22),
  },
  {
    id: "RISK_0901",
    title: "今晚稳赚，进房就能赢",
    author: "未知账号",
    authorType: "玩家",
    source: "玩家投稿",
    authorized: false,
    copyrightRisk: "高",
    status: "待审核",
    game: "双扣",
    gameCluster: "扑克",
    gameplay: ["奖励"],
    region: ["其他"],
    duration: 18,
    orientation: "竖屏",
    primaryType: "活动赛事",
    secondaryType: "诱导内容",
    format: "混剪",
    depth: "浅层",
    topics: ["收益承诺"],
    keywords: ["稳赚", "奖励"],
    highlights: ["夸大收益"],
    emotions: ["刺激"],
    targetStages: ["新增", "低活"],
    targetSkills: ["新手"],
    targetRegions: ["其他"],
    targetInterests: ["棋牌用户"],
    scenes: ["首页推荐流"],
    businessGoal: "转化",
    action: "不建议使用",
    priority: "C",
    quality: 0.42,
    ageHours: 3,
    isUgc: true,
    racePool: "T0",
    authorCredit: 0.18,
    operationBoost: 0,
    strongGuide: true,
    thumbnail: "/thumbs/final-15.jpg",
    metrics: metric(0, 0, 0, 0, 0, 0, 0, 0),
  },
];

export const users: UserProfile[] = [
  {
    id: "U1001",
    name: "温州老玩家",
    stage: "活跃",
    skill: "高手",
    region: "温州",
    recentGames: ["双扣"],
    historyGames: ["双扣", "掼蛋"],
    lostGames: [],
    gameplay: ["炸弹", "残局", "队友配合", "让牌"],
    preferredTypes: ["实战复盘", "技巧教学", "爽点牌局", "地域社交"],
    preferredTopics: ["队友配合", "极限翻盘", "关键决策"],
    preferredEmotions: ["爽", "共鸣", "解气"],
    fastSkippedTypes: ["规则入门"],
    recentAuthors: ["官方运营号"],
    userValidPlayRate: 0.74,
    userFinishRate: 0.58,
    interactionTendency: 0.16,
    gameReturnTendency: 0.21,
    recentLearningIntent: 0.35,
    guideCooldown: false,
  },
  {
    id: "U1002",
    name: "三日未开局用户",
    stage: "低活",
    skill: "进阶",
    region: "浙江",
    recentGames: ["双扣"],
    historyGames: ["双扣"],
    lostGames: ["双扣"],
    gameplay: ["朋友局", "炸弹"],
    preferredTypes: ["棋牌泛娱乐", "爽点牌局", "地域社交"],
    preferredTopics: ["亲友局故事", "极限翻盘", "输赢反应"],
    preferredEmotions: ["搞笑", "轻松", "解气"],
    fastSkippedTypes: ["规则入门", "活动赛事"],
    recentAuthors: [],
    userValidPlayRate: 0.69,
    userFinishRate: 0.64,
    interactionTendency: 0.13,
    gameReturnTendency: 0.12,
    recentLearningIntent: 0.08,
    guideCooldown: false,
  },
  {
    id: "U1003",
    name: "双扣新用户",
    stage: "新增",
    skill: "新手",
    region: "杭州",
    recentGames: ["双扣"],
    historyGames: [],
    lostGames: [],
    gameplay: ["基础流程", "牌型"],
    preferredTypes: ["规则入门", "失误避坑", "棋牌泛娱乐"],
    preferredTopics: ["快速入门", "新手避坑"],
    preferredEmotions: ["清晰", "易懂", "搞笑"],
    fastSkippedTypes: ["技巧教学"],
    recentAuthors: [],
    userValidPlayRate: 0.63,
    userFinishRate: 0.52,
    interactionTendency: 0.07,
    gameReturnTendency: 0.18,
    recentLearningIntent: 0.72,
    guideCooldown: false,
  },
  {
    id: "U1004",
    name: "沉默召回用户",
    stage: "沉默",
    skill: "进阶",
    region: "温州",
    recentGames: [],
    historyGames: ["双扣"],
    lostGames: ["双扣"],
    gameplay: ["朋友局", "地方玩法"],
    preferredTypes: ["地域社交", "棋牌泛娱乐", "爽点牌局"],
    preferredTopics: ["地方玩法", "亲友局故事"],
    preferredEmotions: ["亲切", "共鸣", "搞笑"],
    fastSkippedTypes: ["活动赛事", "规则入门"],
    recentAuthors: [],
    userValidPlayRate: 0.58,
    userFinishRate: 0.61,
    interactionTendency: 0.1,
    gameReturnTendency: 0.08,
    recentLearningIntent: 0.04,
    guideCooldown: true,
  },
];

export const scenes: Scene[] = [
  "首页推荐流",
  "大厅停留",
  "匹配等待",
  "局后结算",
  "退出前",
  "Push落地",
  "游戏详情页",
];

export const defaultConfig: StrategyConfig = {
  rough: {
    gameMatch: 0.3,
    userStageMatch: 0.18,
    sceneMatch: 0.14,
    contentQuality: 0.12,
    recentPerformance: 0.1,
    businessGoalMatch: 0.08,
    freshness: 0.05,
    exploration: 0.03,
  },
  feed: {
    pValidPlay: 0.22,
    pFinish: 0.12,
    pInteraction: 0.08,
    pGameReturn: 0.22,
    pLifecycleImprove: 0.12,
    matchScore: 0.1,
    freshness: 0.05,
    operationBoost: 0.04,
    exploration: 0.05,
    negativePenalty: 0.2,
    fatiguePenalty: 0.15,
    riskPenalty: 0.25,
    hardGuidePenalty: 0.1,
  },
  explorationRatio: 0.1,
  maxSameTypeConsecutive: 3,
  maxSameAuthorPerPage: 2,
  strongGuideInterval: 5,
};
